// Generated by `pnpm design:fonts`: the latin files of the display and body families.
export const FONT_PRELOADS = ["/fonts/anek-latin-latin-6ca258dd.woff2","/fonts/ibm-plex-sans-latin-d8b4e62d.woff2"] as const;
