/**
 * `pnpm design:fonts`: self-hosts the design's fonts (B5.14). Collects every @font-face from the
 * extracted exports (the Google Fonts files the prototypes embed: Anek Latin + Anek Devanagari,
 * variable wght 100–800 / wdth 75–125; IBM Plex Sans, variable wght; IBM Plex Sans Devanagari
 * 400/500/600; IBM Plex Mono 400/500), copies each file once to public/fonts/ and writes
 * app/fonts.css with the same weight, stretch and unicode-range as the prototype, so the
 * browser picks exactly the same file for every character. All SIL OFL 1.1 (public/fonts/OFL.txt).
 */
import { createHash } from "node:crypto";
import { mkdir, readdir, readFile, rm, writeFile } from "node:fs/promises";
import path from "node:path";

interface Face {
  family: string;
  weight: string;
  stretch: string | null;
  subset: string;
  src: string;
  unicodeRange: string | null;
  page: string;
}

const ROOT = process.cwd();
/** Above-the-fold faces: the display and body families, latin subset (the rest load on use). */
const PRELOAD = ["Anek Latin", "IBM Plex Sans"];
const slug = (s: string) => s.toLowerCase().replace(/[^a-z0-9]+/g, "-");

async function main() {
  const faces = new Map<string, Face>();
  for (const f of await readdir(path.join(ROOT, "design/extracted"))) {
    const x = JSON.parse(await readFile(path.join(ROOT, "design/extracted", f), "utf8")) as { page: string; fonts: Array<Omit<Face, "page">> };
    for (const ft of x.fonts ?? []) {
      if (!ft.family || !ft.src) continue;
      const k = `${ft.family}|${ft.weight}|${ft.stretch}|${ft.subset}`;
      if (!faces.has(k)) faces.set(k, { ...ft, page: x.page } as Face);
    }
  }
  await rm(path.join(ROOT, "public/fonts"), { recursive: true, force: true });
  await mkdir(path.join(ROOT, "public/fonts"), { recursive: true });
  const copied = new Map<string, string>();
  const preloads: string[] = [];
  const css: string[] = [
    "/* Generated by `pnpm design:fonts` from the design exports: the same files and",
    "   unicode-ranges as the prototypes, self-hosted (SIL OFL 1.1, public/fonts/OFL.txt). */",
  ];
  const sorted = [...faces.values()].sort((a, b) => `${a.family}${a.weight}${a.subset}`.localeCompare(`${b.family}${b.weight}${b.subset}`));
  for (const f of sorted) {
    // Named by content: one file serves every weight it covers (IBM Plex Sans is variable).
    const bytes = await readFile(path.join(ROOT, "design/unpacked", f.page, "res", `${f.src}.woff2`));
    const file = `${slug(f.family)}-${f.subset}-${createHash("sha1").update(bytes).digest("hex").slice(0, 8)}.woff2`;
    if (!copied.has(file)) {
      await writeFile(path.join(ROOT, "public/fonts", file), bytes);
      copied.set(file, f.src);
    }
    if (f.subset === "latin" && PRELOAD.includes(f.family) && !preloads.includes(file)) preloads.push(file);
    css.push(
      `/* ${f.subset} */`,
      "@font-face {",
      `  font-family: '${f.family}';`,
      "  font-style: normal;",
      `  font-weight: ${f.weight};`,
      ...(f.stretch ? [`  font-stretch: ${f.stretch};`] : []),
      "  font-display: swap;",
      `  src: url('/fonts/${file}') format('woff2');`,
      ...(f.unicodeRange ? [`  unicode-range: ${f.unicodeRange};`] : []),
      "}",
    );
  }
  await writeFile(path.join(ROOT, "app/fonts.css"), css.join("\n") + "\n");
  await writeFile(
    path.join(ROOT, "app/font-preloads.ts"),
    ["// Generated by `pnpm design:fonts`: the latin files of the display and body families.", `export const FONT_PRELOADS = ${JSON.stringify(preloads.map((f) => `/fonts/${f}`))} as const;`, ""].join("\n"),
  );
  const ofl = await readFile(path.join(ROOT, "assets/fonts/OFL.txt"), "utf8");
  const body = ofl.slice(ofl.indexOf("SIL OPEN FONT LICENSE"));
  await writeFile(
    path.join(ROOT, "public/fonts/OFL.txt"),
    [
      "Fonts in this folder, all under the SIL Open Font License, Version 1.1:",
      "",
      "Anek Latin, Anek Devanagari: Copyright 2021 The Anek Project Authors (https://github.com/EkType/Anek)",
      "IBM Plex Sans, IBM Plex Sans Devanagari, IBM Plex Mono: Copyright 2017 IBM Corp. with Reserved Font Name \"Plex\" (https://github.com/IBM/plex)",
      "",
      "Served as the woff2 subsets Google Fonts publishes for these families, unmodified.",
      "",
      body,
    ].join("\n"),
  );
  console.log(`${faces.size} @font-face rules → app/fonts.css; ${copied.size} files → public/fonts/`);
}

main().catch((err) => {
  console.error(err);
  process.exitCode = 1;
});
