/**
 * `pnpm design:tokens`: app/tokens.css from the Developer Handoff's SK.tokens (saakshi-kit.js in
 * the unpacked exports; run design:unpack first). The handoff's own CSS export (DH:449-452):
 * :root (light, plus --radius), .dark and .night, and .light to switch back inside a night
 * section. Also mode-prefixed aliases (--l-*, --d-*, --n-*) for the few places a design uses one
 * mode's colour inside another (a light card over the night map, a night chip over a photo):
 * scripts/design-port.ts emits var(--foreground) when the element's mode matches and the alias
 * otherwise.
 */
import { readdir, readFile, writeFile } from "node:fs/promises";
import path from "node:path";

const ROOT = process.cwd();
const PREFIX = { light: "l", dark: "d", night: "n" } as const;

export async function handoffTokens(): Promise<Record<"light" | "dark" | "night", Record<string, string>>> {
  const dir = path.join(ROOT, "design/unpacked/developer-handoff/res");
  for (const f of await readdir(dir)) {
    if (!f.endsWith(".js")) continue;
    const text = await readFile(path.join(dir, f), "utf8");
    if (!text.startsWith("// Shared helpers for Saakshi")) continue;
    const win: { SK?: { tokens: Record<"light" | "dark" | "night", Record<string, string>> } } = {};
    new Function("window", "document", text)(win, {});
    if (win.SK) return win.SK.tokens;
  }
  throw new Error("saakshi-kit.js not found in design/unpacked/developer-handoff/res: run pnpm design:unpack first.");
}

async function main() {
  const T = await handoffTokens();
  const block = (sel: string, o: Record<string, string>) => `${sel} {\n${Object.entries(o).map(([k, v]) => `  --${k}: ${v};`).join("\n")}\n}`;
  const aliases = Object.entries(T).flatMap(([mode, t]) => Object.entries(t).map(([k, v]) => `  --${PREFIX[mode as keyof typeof PREFIX]}-${k}: ${v};`));
  const css = [
    "/* Generated by `pnpm design:tokens` from the Developer Handoff (SK.tokens). Do not edit. */",
    block(":root,\n.light", { ...T.light, radius: "0.625rem" }),
    block(".dark", T.dark),
    block(".night", T.night),
    `/* One mode's colour used inside another. */\n:root {\n${aliases.join("\n")}\n}`,
    "",
  ].join("\n\n");
  await writeFile(path.join(ROOT, "app/tokens.css"), css);
  console.log(`app/tokens.css: ${Object.values(T).reduce((n, t) => n + Object.keys(t).length, 0)} tokens in 3 modes + ${aliases.length} aliases`);
}

if (process.argv[1] && /design-tokens/.test(process.argv[1]))
  main().catch((err) => {
    console.error(err instanceof Error ? err.message : err);
    process.exitCode = 1;
  });
