/**
 * `pnpm parity:summary`: design/PARITY.md, the committed parity record, from the last
 * `pnpm parity:report` (design/parity/summary.json) and `pnpm parity:boxes` runs
 * (design/parity/boxes-*.json): every page × variant × width with its pixelmatch mean and worst
 * step against the 1.5% gate, box parity, and the notes that explain each known difference.
 */
import { readdir, readFile, writeFile } from "node:fs/promises";
import path from "node:path";

interface Pair {
  design: string;
  variant: string;
  width: number;
  steps: number;
  pixel: number;
  worstPixel: number;
  pass: boolean;
}

/** Why a run differs, where it does (each also in ENGINEERING.md's journal). */
const NOTES: Record<string, string> = {
  "demo-entry/default": "The prototype scatters the manager loop's tiles with Math.random (DE:471) and this is a real-time scroll capture: the scatter differs every run (issue G6). The deterministic still is `reduced`.",
  "demo-entry/loops": "Frames 0–1.5 s show the prototype's Math.random scatter (G6); from 2 s, 0–0.1%.",
  "spot-page/default": "The trend's points sit by time (Phase 8 A3: adaptive time axis) where the prototype spaces them by index.",
  "qr-poster/default": "At 390 the prototype's own capture shows a broken logo image.",
  "saakshi-app/drawer": "At 390 (a touch screen) the loupe button is hidden (C25: desktop only); at 1440 its label drops the design's 'P1' review mark (B5.11). Same for drawer-exploded.",
};
const EXPECTED = new Set(["demo-entry/default", "demo-entry/loops"]);

async function main() {
  const dir = path.join(process.cwd(), "design", "parity");
  const s = JSON.parse(await readFile(path.join(dir, "summary.json"), "utf8")) as { generatedAt: string; gate: number; pairs: Pair[]; unpairedDesign: string[] };
  const boxes: Array<{ page: string; width: number; compared: number; over: number; tolerance: number }> = [];
  for (const f of (await readdir(dir)).filter((x) => /^boxes-.+-\d+\.json$/.test(x)).sort()) {
    const b = JSON.parse(await readFile(path.join(dir, f), "utf8")) as { width: number; tolerance: number; compared: number; over: number };
    boxes.push({ page: f.replace(/^boxes-|-\d+\.json$/g, ""), width: b.width, compared: b.compared, over: b.over, tolerance: b.tolerance });
  }
  const pairs = [...s.pairs].sort((a, b) => a.design.localeCompare(b.design) || a.variant.localeCompare(b.variant) || b.width - a.width);
  const runs = pairs.length;
  const passing = pairs.filter((p) => p.pixel <= s.gate).length;
  const unexplained = pairs.filter((p) => p.pixel > s.gate && !EXPECTED.has(`${p.design}/${p.variant}`));
  const pagesShown = [...new Set(pairs.map((p) => p.design))];

  const md: string[] = [];
  md.push("# Design parity");
  md.push("");
  md.push(`Generated by \`pnpm parity:summary\` from the parity run of ${s.generatedAt.slice(0, 16).replace("T", " ")} UTC (\`pnpm parity:report\`, \`pnpm parity:boxes\`). Each run compares a page's \`/dev/parity/<page>\` fixture (our components on the prototype's own data) with the prototype export, frame by frame (pixelmatch), against the ${s.gate}% gate. Diff images: \`design/parity/diff/\` (not committed; regenerate with the commands above).`);
  md.push("");
  md.push(`**${runs} runs on ${pagesShown.length} pages: ${passing} within the gate.** ${unexplained.length ? `${unexplained.length} unexplained.` : "Every run over the gate is explained below; none is unexplained."}`);
  md.push("");
  md.push("| page | variant | width | steps | mean % | worst % | gate |");
  md.push("|---|---|---|---|---|---|---|");
  for (const p of pairs) md.push(`| ${p.design} | ${p.variant} | ${p.width} | ${p.steps} | ${p.pixel} | ${p.worstPixel} | ${p.pixel <= s.gate ? "pass" : EXPECTED.has(`${p.design}/${p.variant}`) ? "over (explained)" : "over"} |`);
  md.push("");
  md.push("## Bounding boxes");
  md.push("");
  md.push("Element boxes paired by id, section label, hooks, headings and (with `--text`) leaf text, against the export: ±2 px at 1440, ±1 px at 390.");
  md.push("");
  md.push("| page | width | compared | over tolerance |");
  md.push("|---|---|---|---|");
  for (const b of boxes) md.push(`| ${b.page} | ${b.width} | ${b.compared} | ${b.over} |`);
  md.push("");
  md.push("## Notes");
  md.push("");
  for (const [k, v] of Object.entries(NOTES)) md.push(`- **${k}**: ${v}`);
  md.push(`- Not compared (reference and spec pages, brief B2): ${s.unpairedDesign.join(", ")}.`);
  md.push("");
  await writeFile(path.join(process.cwd(), "design", "PARITY.md"), md.join("\n"));
  console.log(`design/PARITY.md: ${runs} runs, ${passing} within ${s.gate}%, ${unexplained.length} unexplained; ${boxes.length} box runs.`);
}

main().catch((err) => {
  console.error(err instanceof Error ? err.message : err);
  process.exitCode = 1;
});
